export const SET_PROVIDER_START = "SET_PROVIDER_START";
export const MM_INSTALLED = "MM_INSTALLED";
export const SET_PROVIDER_SUCCESS = "SET_PROVIDER_SUCCESS";
export const SET_PROVIDER_FAIL = "SET_PROVIDER_FAIL";

export const START_VIEW_UPDATE = "START_VIEW_UPDATE";
export const UPDATE_CLOSED = "UPDATE_CLOSED";
export const UPDATE_UNTIED = "UPDATE_UNTIED";
export const UPDATE_OPENED = "UPDATE_OPENED";
export const UPDATE_PRIZES = "UPDATE_PRIZES";
export const NO_CONNECTION = "NO_CONNECTION";
export const CLOSED_ERROR = "CLOSED_ERROR";
export const UNTIED_ERROR = "UNTIED_ERROR";
export const OPENED_ERROR = "OPENED_ERROR";
export const PRIZES_ERROR = "PRIZES_ERROR";
export const GENERAL_ERROR = "GENERAL_ERROR";

export const START_UNTIE_BAG = "START_UNTIE_BAG";
export const START_OPEN_BAG = "START_OPEN_BAG";
export const UNTIE_BAG_SUCCESS = "UNTIE_BAG_SUCCESS";
export const OPEN_BAG_SUCCESS = "OPEN_BAG_SUCCESS";
export const UNTIE_BAG_FAIL = "UNTIE_BAG_FAIL";
export const OPEN_BAG_FAIL = "OPEN_BAG_FAIL";
export const NO_BAGS_TO_UNTIE = "NO_BAGS_TO_UNTIE";
export const NO_BAGS_TO_OPEN = "NO_BAGS_TO_OPEN";
